# Generated by Django 5.0 on 2023-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('profileSeeking', models.TextField()),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('rel', models.CharField(max_length=20)),
                ('mto', models.CharField(max_length=20)),
            ],
        ),
    ]
