# Generated by Django 5.0 on 2023-12-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='gender',
            new_name='gender_m',
        ),
    ]
