# Generated by Django 5.0 on 2023-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_registeruser_gender_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='gender_m',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
