# Generated by Django 5.0 on 2023-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_registeruser_gender_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='password',
            field=models.TextField(default='', max_length=30),
        ),
    ]
