# Generated by Django 4.2.7 on 2023-11-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('auther_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=20)),
                ('author_email', models.EmailField(max_length=254)),
                ('auther_pp', models.ImageField(upload_to='')),
                ('author_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisionapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisionapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_info', models.TextField()),
                ('book_price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
                ('book_desc', models.TextField()),
                ('book_page', models.IntegerField()),
                ('book_image', models.ImageField(upload_to='')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisionapp.category')),
            ],
        ),
    ]
